[project]
name = "nrl-sdk"
version = "0.1.0"
description = "A top level package for the NRL SDK"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.15",
    "mkdocstrings[python]>=0.29.1",
]
