name: Release
on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        options:
          - nrl-sdk-lib
          - tools/nrl-test-data-generator
        description: "The package to release"
        required: true

jobs:
  release-build:
    name: Upload release to PyPI
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.7.20"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build and publish the ${{ github.event.inputs.package }} package
        run: |
          cd ${{ github.event.inputs.package }}
          uv build

      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v5
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
