name: Release
on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        options:
          - nrl-sdk-lib
        description: "The package to release"
        required: true

permissions:
  id-token: write

jobs:
  release:
    name: python
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.7.20"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build and publish the ${{ github.event.inputs.package }} package
        run: |
          cd ${{ github.event.inputs.package }}
          uv build
          uv publish
